### ISSUE TITLE
Spinner and progress bar never stop after failed profile save

### ISSUE THREAD

**Issue by jsakuda** [epochtalk/ept-frontend#12]
On Safari:

1) Try to edit profile and set Gender to something weird like "Blueberry"
2) Save

The UI will pop up a message that profile could not be saved and then the progress bar will slowly progress most of the way across the top of the screen (without finishing) and the spinner will keep spinning.

**Comment by taesup** [comment]
Fixed in 941e188825cb5a3c9fcb9798f5ae9961f56c2fe5
